version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vehicleuser
      POSTGRES_PASSWORD: vehiclepass
      POSTGRES_DB: vehicle_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./vehicle_maintenance_project/backend
    environment:
      DATABASE_URL: postgres://vehicleuser:vehiclepass@db:5432/vehicle_db
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build: ./vehicle_maintenance_project/frontend
    environment:
      REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data:
