version: "3.8"

services:
  db:
    image: postgres:15
    container_name: vehicle_maintenance_project-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicle_maintenance
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vehicle_maintenance"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: vehicle_maintenance_project-backend-1
    command: >
      sh -c "until pg_isready -h db -U postgres; do echo waiting for db; sleep 2; done &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vehicle_maintenance
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    container_name: vehicle_maintenance_project-frontend-1
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
